[project]
name = "alien"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Simon Garton", email = "simon.garton@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
alien = "alien:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
